## Enable metrics
## https://kyverno.io/docs/monitoring/

podAnnotations:
  prometheus.io/path: "/metrics" # Added for otel discover/scraping
  prometheus.io/port: "8000:"
  prometheus.io/scheme: "http" # Added for otel discover/scraping
  prometheus.io/scrape: "true"

admissionController:
  metricsService:
    create: true

backgroundController:
  metricsService:
    create: true

cleanupController:
  metricsService:
    create: true

reportsController:
  metricsService:
    create: true
